import json
from importlib.machinery import SourceFileLoader


def load_dictionary(path):
    return eval(open(path, 'r').read())


def load_python_file(path):
    return SourceFileLoader("", path).load_module()


def write_sublimious_file(path, content):
    with open(path, "w") as f:
        f.write("// Generated by sublimious. Don't touch. \n")
        f.write("// Edit ~/.sublimious instead. \n")
        f.write(content)
